#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LDrive,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LLauncher,     tmotorVex393TurboSpeed_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RLauncher,     tmotorVex393TurboSpeed_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port4,           Lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LiftFeeder,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RDrive,        tmotorVex393_HBridge, openLoop)
#pragma config(MotorPidSetting,  port2,  50, 10, 1000, 12, 10,   60, 0, 0)
#pragma config(MotorPidSetting,  port3,  50, 10, 1000, 12, 10,   60, 0, 0)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// We are using the following motor ports:
// Ports 1 & 10: Drive Wheels
// Ports 2 & 3:  Launcher (I2C Control)
// Port 4:       Lift
// Port 5:       Feeder
// Port 6:       Launcher Feed wheel
//
// The following are mapped on the hand controller:
// Left Joystick:  Left Drive Wheel
// Right Joystick: Right Drive Wheel
// Button 5U:      Turn off feeder, turn on lift mechanism
// Button 5D:      Reverse Feeder/Lift to clear jams etc.
// Button 6U:      Speed Up Launcher
// Button 6D:      Slow Down Launcher
// Button 8U:      Max Launcher Speed
// Button 8D:      Min Launcher Speed
// Button 8L:      Launcher Off
// Button 8R:      Medium Launcher Speed


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(180)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

int launcherSpeed = 0;   // Set speed of Launcher
int defaultLSpeed = 127; // Value that scores from the corner
int liftSpeed = 50;

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	launcherSpeed = defaultLSpeed;

	//Start the launcher, wait for it to speed up
	motor[LLauncher] = launcherSpeed;
	motor[RLauncher] = launcherSpeed;
	wait1Msec(5000);

	//Start lift
	motor[Lift] = liftSpeed;
	motor[LiftFeeder] = 127;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	launcherSpeed = 127;
	while (true)
	{
		// Joystic Control:
		motor[RDrive] = vexRT[Ch2]; //Motor port 10 speed is determined by Ch2 on the VEXnet Transmitter
		motor[LDrive] = vexRT[Ch3]; //Motor port 1  speed is determined by Ch3 on the VEXnet Transmitter

		// Lift Control:
		if(vexRT[Btn5U] == 1)      //If button 5U is pressed - stop feeder, start lift
		{
			motor[Lift] = liftSpeed;
			motor[Intake] = 0;
			motor[LiftFeeder] = 127;
		}
		else if(vexRT[Btn5D] == 1) //If button 5D is pressed - reverse both to clear jams
		{
			motor[Lift] = -60;
			motor[Intake] = -127;
			motor[LiftFeeder] = 0;
		}
		else                       //If neither buttons 5U or 5D are pressed - run feeder, lift off
		{
			motor[Lift] = 0;
			motor[Intake] = 127;
			motor[LiftFeeder] = 0;
		}

		// Launcher Speed Control
		if ((vexRT[Btn6U] == 1) && (launcherSpeed < 127))       // Speed Up
		{
			launcherSpeed++;
			wait1Msec(200);
		}
		else if ((vexRT[Btn6D] == 1) && (launcherSpeed > 80))   // Slow Down
		{
			launcherSpeed--;
			wait1Msec(200);
		}

		if (vexRT[Btn8U] == 1)       // MAX Speed
			launcherSpeed = 127;
		else if (vexRT[Btn8D] == 1)  // MIN Speed
			launcherSpeed = 100;
		else if (vexRT[Btn8L] == 1)  // OFF
			launcherSpeed = 0;
		else if (vexRT[Btn8R] == 1)  // MEDIUM Speed
			launcherSpeed = 112;


		if (vexRT[Btn7L] == 1)  // Reverse for feeding by hand
			motor[LiftFeeder] = -70;

		// Keep Launcher Running:
		motor[LLauncher] = launcherSpeed;
		motor[RLauncher] = launcherSpeed;

		wait1Msec(50);
	}
}
