#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// We are using the following motor ports:
// Ports 1 & 10: Drive Wheels
// Ports 2 & 3:  Launcher
// Port 4:       Lift
// Port 5:       Feeder
// Port 6:       Launcher Feed wheel
//
// The following are mapped on the hand controller:
// Left Joystick:  Left Drive Wheel
// Right Joystick: Right Drive Wheel
// Button 5U:      Turn off feeder, turn on lift mechanism
// Button 5D:      Reverse Feeder/Lift to clear jams etc.
// Button 6U:      Speed Up Launcher
// Button 6D:      Slow Down Launcher
// Button 8U:      Max Launcher Speed
// Button 8D:      Min Launcher Speed


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(180)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

int launcherSpeed = 100; // Set speed of Launcher

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Reverse motor defaults on the following
	bMotorReflected[port1] = true;
	bMotorReflected[port4] = true;
	bMotorReflected[port5] = true;
	bMotorReflected[port2] = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//Start the launcher, wait for it to speed up
	motor[port2] = launcherSpeed;
	motor[port3] = launcherSpeed;
	wait1Msec(5000);

	//Start lift
	motor[port4] = 50;
	motor[port6] = 127;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		// Joystic Control:
		motor[port10] = vexRT[Ch2]; //Motor port 10 speed is determined by Ch2 on the VEXnet Transmitter
		motor[port1]  = vexRT[Ch3]; //Motor port 1  speed is determined by Ch3 on the VEXnet Transmitter

		// Lift Control:
		if(vexRT[Btn5U] == 1)      //If button 5U is pressed - stop feeder, start lift
		{
			motor[port4] = 50;
			motor[port5] = 0;
			motor[port6] = 127;
		}
		else if(vexRT[Btn5D] == 1) //If button 5D is pressed - reverse both to clear jams
		{
			motor[port4] = -60;
			motor[port5] = -60;
			motor[port6] = 0;
		}
		else                       //If neither buttons 5U or 5D are pressed - run feeder, lift off
		{
			motor[port4] = 0;
			motor[port5] = 127;
			motor[port6] = 0;
		}

		// Launcher Speed Control
		if ((vexRT[Btn6U] == 1) && (launcherSpeed < 127))        // Speed Up
			launcherSpeed++;
		else if ((vexRT[Btn6D] == 1) && (launcherSpeed > 80))   // Slow Down
			launcherSpeed--;

		if (vexRT[Btn8U] == 1)       // MAX Speed
			launcherSpeed = 127;
		else if (vexRT[Btn8D] == 1)  // MIN Speed
			launcherSpeed = 80;

		// Keep Launcher Running:
		motor[port2] = launcherSpeed;
		motor[port3] = launcherSpeed;

		wait1Msec(50);

	}
}
